# -*- coding: utf-8 -*-
"""
/***************************************************************************
 xplanung24
                                 A QGIS plugin
 Diese Plugin ermöglicht es Ihnen XPläne aus QGIS automatisch in Ihren XPlanung24 account zu übertrage bzw. abzurufen
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-10-10
        copyright            : (C) 2024 by Bau.Land.XPlan Gbr
        email                : admin@xplanung24.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


import os, sys

libs_path = os.path.join(os.path.dirname(__file__), "libs")
if libs_path not in sys.path:
    sys.path.insert(0, libs_path)

# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load xplanung24 class from file xplanung24.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .xplanung24 import xplanung24
    return xplanung24(iface)
